// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmoJNFcNLo6Oqv7LQJQGt_yPcY3HH84VQ',
    appId: '1:346403249512:web:ddfc550222cbf65ebf4add',
    messagingSenderId: '346403249512',
    projectId: 'memeland-7125c',
    authDomain: 'memeland-7125c.firebaseapp.com',
    storageBucket: 'memeland-7125c.firebasestorage.app',
    measurementId: 'G-BYE8MZ0Y56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS74Z9LWMSg8F6_Zxr4BCTX6F5QQ6YeDY',
    appId: '1:346403249512:android:eff319c999ede801bf4add',
    messagingSenderId: '346403249512',
    projectId: 'memeland-7125c',
    storageBucket: 'memeland-7125c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7dYcftmbQWrXHOahsZXxPD3_6PyTmqNI',
    appId: '1:346403249512:ios:150f26e15be7b44fbf4add',
    messagingSenderId: '346403249512',
    projectId: 'memeland-7125c',
    storageBucket: 'memeland-7125c.firebasestorage.app',
    iosBundleId: 'com.pranta.memeland',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7dYcftmbQWrXHOahsZXxPD3_6PyTmqNI',
    appId: '1:346403249512:ios:150f26e15be7b44fbf4add',
    messagingSenderId: '346403249512',
    projectId: 'memeland-7125c',
    storageBucket: 'memeland-7125c.firebasestorage.app',
    iosBundleId: 'com.pranta.memeland',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmoJNFcNLo6Oqv7LQJQGt_yPcY3HH84VQ',
    appId: '1:346403249512:web:9e4d03b1198f53ffbf4add',
    messagingSenderId: '346403249512',
    projectId: 'memeland-7125c',
    authDomain: 'memeland-7125c.firebaseapp.com',
    storageBucket: 'memeland-7125c.firebasestorage.app',
    measurementId: 'G-RBR7GRRTP3',
  );

}